"""settings preferences and reports

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 19:31:26.107190

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column("reported_user_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'::text"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "reason = ANY (ARRAY['harassment'::text, 'spam'::text, 'fake_profile'::text, 'inappropriate_content'::text, 'underage'::text, 'other'::text])",
            name=op.f("reports_reason_check"),
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['open'::text, 'reviewing'::text, 'resolved'::text, 'dismissed'::text])",
            name=op.f("reports_status_check"),
        ),
        sa.CheckConstraint("reporter_id <> reported_user_id", name=op.f("reports_not_self")),
        sa.ForeignKeyConstraint(
            ["reported_user_id"], ["profiles.id"], name=op.f("reports_reported_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["profiles.id"], name=op.f("reports_reporter_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reports_pkey")),
    )
    op.create_index("reports_reported_user_idx", "reports", ["reported_user_id", "created_at"], unique=False)
    op.create_index("reports_reporter_idx", "reports", ["reporter_id"], unique=False)
    op.add_column(
        "user_settings",
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "preferences")
    op.drop_index("reports_reporter_idx", table_name="reports")
    op.drop_index("reports_reported_user_idx", table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
