"""baseline schema

Portable equivalent of the Supabase public schema after supabase/migrations/20261009130000
(see docs/database/migrations.md). The FK from profiles.id to auth.users, RLS policies and
Supabase auth triggers are not included; tests/test_migrations.py checks parity.

Revision ID: 0001
Revises:
Create Date: 2026-10-09 18:29:53.450706

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.models import TABLES_WITH_UPDATED_AT

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("interests", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("streak_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("gender", sa.Text(), nullable=True),
        sa.Column("gender_preference", sa.Text(), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("occupation", sa.Text(), nullable=True),
        sa.Column("education", sa.Text(), nullable=True),
        sa.Column("exercise", sa.Text(), nullable=True),
        sa.Column("drinking_habit", sa.Text(), nullable=True),
        sa.Column("smoking_habit", sa.Text(), nullable=True),
        sa.Column("relationship_goal", sa.Text(), nullable=True),
        sa.Column("communication_style", sa.Text(), nullable=True),
        sa.Column("love_language", sa.Text(), nullable=True),
        sa.Column("zodiac_sign", sa.Text(), nullable=True),
        sa.Column("hometown", sa.Text(), nullable=True),
        sa.Column("pronouns", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("age_range_min", sa.Integer(), server_default=sa.text("18"), nullable=True),
        sa.Column("age_range_max", sa.Integer(), server_default=sa.text("35"), nullable=True),
        sa.Column("distance_preference", sa.Integer(), server_default=sa.text("25"), nullable=True),
        sa.Column("show_me_verified_only", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("show_age", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.Column("onboarding_completed", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("profiles_pkey")),
    )
    op.create_table(
        "ai_chat_history",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("message_content", sa.Text(), nullable=False),
        sa.Column("message_type", sa.Text(), server_default=sa.text("'text'::text"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("ai_chat_history_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ai_chat_history_pkey")),
    )
    op.create_index("ai_chat_history_user_created_idx", "ai_chat_history", ["user_id", "created_at"], unique=False)
    op.create_table(
        "blocked_users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("blocked_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["blocked_user_id"],
            ["profiles.id"],
            name=op.f("blocked_users_blocked_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("blocked_users_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("blocked_users_pkey")),
        sa.UniqueConstraint("user_id", "blocked_user_id", name=op.f("blocked_users_user_id_blocked_user_id_key")),
    )
    op.create_index("blocked_users_blocked_idx", "blocked_users", ["blocked_user_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("matched_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'::text"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_user_id"],
            ["profiles.id"],
            name=op.f("matches_matched_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], name=op.f("matches_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("matches_pkey")),
        sa.UniqueConstraint("user_id", "matched_user_id", name=op.f("matches_user_id_matched_user_id_key")),
    )
    op.create_index("matches_matched_user_idx", "matches", ["matched_user_id"], unique=False)
    op.create_index(
        "matches_pair_unique",
        "matches",
        [
            sa.literal_column("least(user_id, matched_user_id)"),
            sa.literal_column("greatest(user_id, matched_user_id)"),
        ],
        unique=True,
    )
    op.create_table(
        "profile_images",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("is_visible", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], name=op.f("profile_images_profile_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profile_images_pkey")),
    )
    op.create_index("profile_images_profile_idx", "profile_images", ["profile_id", "position"], unique=False)
    op.create_table(
        "profile_onboarding",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("completed", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("current_step", sa.Text(), server_default=sa.text("'basics'::text"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("profile_onboarding_profile_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profile_onboarding_pkey")),
        sa.UniqueConstraint("profile_id", name=op.f("profile_onboarding_profile_id_key")),
    )
    op.create_table(
        "safety_contacts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("contact_name", sa.Text(), nullable=False),
        sa.Column("contact_phone", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("safety_contacts_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("safety_contacts_pkey")),
    )
    op.create_index("safety_contacts_user_idx", "safety_contacts", ["user_id"], unique=False)
    op.create_table(
        "streaks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("streak_count", sa.Integer(), server_default=sa.text("1"), nullable=True),
        sa.Column("likes_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("comments_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], name=op.f("streaks_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("streaks_pkey")),
    )
    op.create_index("streaks_user_created_idx", "streaks", ["user_id", "created_at"], unique=False)
    op.create_table(
        "swipes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("swiped_user_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "direction = ANY (ARRAY['left'::text, 'right'::text, 'super'::text])",
            name=op.f("swipes_direction_check"),
        ),
        sa.CheckConstraint("user_id <> swiped_user_id", name=op.f("swipes_not_self")),
        sa.ForeignKeyConstraint(
            ["swiped_user_id"], ["profiles.id"], name=op.f("swipes_swiped_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], name=op.f("swipes_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("swipes_pkey")),
        sa.UniqueConstraint("user_id", "swiped_user_id", name=op.f("swipes_user_id_swiped_user_id_key")),
    )
    op.create_index("swipes_swiped_idx", "swipes", ["swiped_user_id"], unique=False)
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("feedback_type", sa.Text(), nullable=False),
        sa.Column("feedback_content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("user_feedback_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_feedback_pkey")),
    )
    op.create_index("user_feedback_user_idx", "user_feedback", ["user_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.Column("location_sharing", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("show_online_status", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.Column("theme", sa.Text(), server_default=sa.text("'system'::text"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("user_settings_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_settings_pkey")),
        sa.UniqueConstraint("user_id", name=op.f("user_settings_user_id_key")),
    )
    op.create_table(
        "date_plans",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("date_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("partner_name", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'planned'::text"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("location_sharing_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["safety_contacts.id"], name=op.f("date_plans_contact_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], name=op.f("date_plans_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("date_plans_pkey")),
    )
    op.create_index("date_plans_user_idx", "date_plans", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), server_default=sa.text("'text'::text"), nullable=True),
        sa.Column("media_url", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], name=op.f("messages_match_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["profiles.id"], name=op.f("messages_sender_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    op.create_index("messages_match_created_idx", "messages", ["match_id", "created_at"], unique=False)
    op.create_index("messages_sender_idx", "messages", ["sender_id"], unique=False)
    op.create_table(
        "streak_likes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("streak_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["streak_id"], ["streaks.id"], name=op.f("streak_likes_streak_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("streak_likes_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("streak_likes_pkey")),
        sa.UniqueConstraint("user_id", "streak_id", name=op.f("streak_likes_user_id_streak_id_key")),
    )
    op.create_index("streak_likes_streak_idx", "streak_likes", ["streak_id"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          NEW.updated_at = now();
          RETURN NEW;
        END;
        $$
        """
    )
    for table in TABLES_WITH_UPDATED_AT:
        op.execute(
            f"CREATE TRIGGER {table}_set_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in TABLES_WITH_UPDATED_AT:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_set_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("streak_likes_streak_idx", table_name="streak_likes")
    op.drop_table("streak_likes")
    op.drop_index("messages_sender_idx", table_name="messages")
    op.drop_index("messages_match_created_idx", table_name="messages")
    op.drop_table("messages")
    op.drop_index("date_plans_user_idx", table_name="date_plans")
    op.drop_table("date_plans")
    op.drop_table("user_settings")
    op.drop_index("user_feedback_user_idx", table_name="user_feedback")
    op.drop_table("user_feedback")
    op.drop_index("swipes_swiped_idx", table_name="swipes")
    op.drop_table("swipes")
    op.drop_index("streaks_user_created_idx", table_name="streaks")
    op.drop_table("streaks")
    op.drop_index("safety_contacts_user_idx", table_name="safety_contacts")
    op.drop_table("safety_contacts")
    op.drop_table("profile_onboarding")
    op.drop_index("profile_images_profile_idx", table_name="profile_images")
    op.drop_table("profile_images")
    op.drop_index("matches_pair_unique", table_name="matches")
    op.drop_index("matches_matched_user_idx", table_name="matches")
    op.drop_table("matches")
    op.drop_index("blocked_users_blocked_idx", table_name="blocked_users")
    op.drop_table("blocked_users")
    op.drop_index("ai_chat_history_user_created_idx", table_name="ai_chat_history")
    op.drop_table("ai_chat_history")
    op.drop_table("profiles")
    # ### end Alembic commands ###
