"""profile location

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-09 20:11:49.416814

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("latitude", sa.Double(), nullable=True))
    op.add_column("profiles", sa.Column("longitude", sa.Double(), nullable=True))
    op.add_column("profiles", sa.Column("location_updated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate does not detect CHECK constraints; keep in sync with the model and the Supabase migration.
    op.create_check_constraint(
        "coordinates_check",  # the naming convention prefixes the table name
        "profiles",
        "(latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("coordinates_check", "profiles", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "location_updated_at")
    op.drop_column("profiles", "longitude")
    op.drop_column("profiles", "latitude")
    # ### end Alembic commands ###
