"""moderator role and report review

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-10 11:56:22.300346

Adds operator-granted roles (only 'moderator' so far) and records who reviewed a report, when, and with what note.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("granted_by", sa.Text(), nullable=True),
        sa.CheckConstraint("role = 'moderator'::text", name=op.f("user_roles_role_check")),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], name=op.f("user_roles_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role", name=op.f("user_roles_pkey")),
    )
    op.add_column("reports", sa.Column("reviewed_by", sa.UUID(), nullable=True))
    op.add_column("reports", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("reports", sa.Column("resolution_note", sa.Text(), nullable=True))
    op.create_index("reports_status_created_idx", "reports", ["status", "created_at"], unique=False)
    op.create_foreign_key(
        op.f("reports_reviewed_by_fkey"), "reports", "profiles", ["reviewed_by"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("reports_reviewed_by_fkey"), "reports", type_="foreignkey")
    op.drop_index("reports_status_created_idx", table_name="reports")
    op.drop_column("reports", "resolution_note")
    op.drop_column("reports", "reviewed_at")
    op.drop_column("reports", "reviewed_by")
    op.drop_table("user_roles")
    # ### end Alembic commands ###
