"""notifications

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 19:46:22.584408

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("match_id", sa.UUID(), nullable=True),
        sa.Column("streak_id", sa.UUID(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "type = ANY (ARRAY['match'::text, 'message'::text, 'streak_like'::text])",
            name=op.f("notifications_type_check"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["profiles.id"], name=op.f("notifications_actor_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("notifications_match_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["streak_id"], ["streaks.id"], name=op.f("notifications_streak_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("notifications_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notifications_pkey")),
    )
    op.create_index("notifications_user_created_idx", "notifications", ["user_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("notifications_user_created_idx", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
